services:
  app:
    image: ghcr.io/omar-the-junior/salam-hack-2026:main
    pull_policy: always
    restart: unless-stopped
    working_dir: /var/www
    expose:
      - 80
    volumes:
      - storage:/var/www/storage:rw
      - bootstrap-cache:/var/www/bootstrap/cache:rw
    networks:
      - dokploy-network
    env_file:
      - .env

volumes:
  storage:
  bootstrap-cache:

networks:
  dokploy-network:
    external: true
